# Generated by Django 3.1.2 on 2020-10-07 16:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0004_auto_20201006_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
