# Generated by Django 3.1.2 on 2020-10-07 21:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0005_article_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='liked_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
